plugins:
  - removeTitle: true
  - removeStyleElement: true
  - removeAttrs:
      attrs:
        - id
        - class
        - data-name
  - removeEmptyContainers: true
  - sortAttrs: true
  - removeUselessDefs: true
  - removeEmptyText: true
  - removeEditorsNSData: true
  - removeEmptyAttrs: true
  - removeHiddenElems: true
